const { profile } = require('../models');

// Review foreign key relationship
const profileData = [
    {
        id: 1,
        accountId: 1,
        first_name: 'Ethan',
        last_name: 'Smith',
        age: 21,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Manhattan',
        green_flag: "I have an extensive collection of films from various genres, and I love nothing more than cozying up for a movie night, complete with popcorn and in-depth discussions about the plot, characters, and cinematic techniques.",
        yellow_flag: "It is important that people understand the deeper symbolism in films. If you cannot appreciate the intricacies of movie's subtext, we probably won't have much to talk about.",
        red_flag: "I expect my partner to watch every movie I recommend and be available for lengthy discussions about them. If you can't keep up with my movie-watching pace, it won't work out.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456166/Portraits/Male/ryan-hoffman-qyJhk8H8NSQ-unsplash_1_ga507k.jpg',
    },
    {
        id: 2,
        accountId: 2,
        first_name: 'Liam',
        last_name: 'Johnson',
        age: 31,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Manhattan',
        green_flag: "Staying up-to-date with the latest gadgets and technology trends is a part of my identity. Whether it's exploring virtual reality or tinkering with new gadgets, I'd love to explore the digital frontier together.",
        yellow_flag: "With so much innovation in the world to keep track of, I don't often have a lot of time for socializing. But I'm sure it won't be a problem if you share my deep passion for tech.",
        red_flag: "As a backup to this whole dating thing, I'm building a girlfriend using a combination of AI, Vaporware, and 3D printing. It's like Weird Science, but creepy and less charming.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456165/Portraits/Male/edward-howell-CH4TaXDYfYM-unsplash_gtuciv.jpg',
    },
    {
        id: 3,
        accountId: 3,
        first_name: 'Noah',
        last_name: 'Williams',
        age: 39,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Manhattan',
        green_flag: "I love experimenting in the kitchen and preparing delicious meals for us to enjoy together, creating memorable dining experiences.",
        yellow_flag: "Microwave Cooking for One is my favorite cookbook.",
        red_flag: "Vegetables are bad for the humors.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456162/Portraits/Male/jurica-koletic-7YVZYZeITc8-unsplash_zabf5m.jpg',
    },
    {
        id: 4,
        accountId: 4,
        first_name: 'Ben',
        last_name: 'Jones',
        age: 29,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Long Island',
        green_flag: " I have a deep affection for animals, and I'm more than happy to embrace your furry friends as part of our lives.",
        yellow_flag: "If given the option, I always choose the companionship of animals over that of humans.",
        red_flag: "I currently own upwards of 500 turtles.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456159/Portraits/Male/christian-buehner-DItYlc26zVI-unsplash_milcmn.jpg',
    },
    {
        id: 5,
        accountId: 5,
        first_name: 'Sam',
        last_name: 'Brown',
        age: 25,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Brooklyn',
        green_flag: "I enjoy surprising you with spontaneous gestures of love and affection, keeping the romance alive in our relationship.",
        yellow_flag: "I, however, do not like being surprised.",
        red_flag: "My preferred method of conveying affection is spontaneous mariachi band performances",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456156/Portraits/Male/taylor-8Vt2haq8NSQ-unsplash_wpy6df.jpg',
    },
    {
        id: 5,
        accountId: 5,
        first_name: 'Sam',
        last_name: 'Brown',
        age: 25,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Brooklyn',
        green_flag: "I enjoy surprising you with spontaneous gestures of love and affection, keeping the romance alive in our relationship.",
        yellow_flag: "I, however, do not like being surprised.",
        red_flag: "My preferred method of conveying affection is spontaneous mariachi band performances",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456156/Portraits/Male/taylor-8Vt2haq8NSQ-unsplash_wpy6df.jpg',
    },
    {
        id: 6,
        accountId: 6,
        first_name: 'Jackson',
        last_name: 'Davis',
        age: 35,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Brooklyn',
        green_flag: "I am financially responsible: I believe in managing money wisely, ensuring our financial stability and future security.",
        yellow_flag: "The folder in which I keep my investment portfolio is titled To the Moon",
        red_flag: "I am THE owner of an exclusive Bubbles the Chimp NFT officially issued by the Jackson estate",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456156/Portraits/Male/albert-dera-ILip77SbmOE-unsplash_sjlm5u.jpg',
    },
    {
        id: 7,
        accountId: 7,
        first_name: 'Alex',
        last_name: 'Miller',
        age: 31,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Queens',
        green_flag: "I prioritize a healthy lifestyle and am dedicated to supporting your well-being and fitness goals.",
        yellow_flag: "I run at least a half marathon every day",
        red_flag: "All of my joints have been replaced, and I am now more machine than man.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456156/Portraits/Male/ludovic-migneault-4uj3iZ5m084-unsplash_ai0lin.jpg',
    },
    {
        id: 8,
        accountId: 8,
        first_name: 'Daniel',
        last_name: 'Wilson',
        age: 21,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Queens',
        green_flag: "I'm open to trying new things and experiencing life's adventures together, whether it's exploring new places or trying new cuisines.",
        yellow_flag: "I can live anywhere and eat just about anything.",
        red_flag: "I am the first selectman of an underground society of mole people.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456155/Portraits/Male/midas-hofstra-tidSLv-UaNs-unsplash_rworug.jpg',
    },
    {
        id: 9,
        accountId: 9,
        first_name: 'Mason',
        last_name: 'Moore',
        age: 34,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Brooklyn',
        green_flag: " I'm attuned to your emotions and can provide emotional support when you need it most.",
        yellow_flag: "I'm not comfortable making decisions without consulting my psychic first",
        red_flag: "Why did they feel the need to put 5G in the vaccines when the reception coming from my fillings is so crisp?",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456155/Portraits/Male/midas-hofstra-tidSLv-UaNs-unsplash_rworug.jpg',
    },
    {
        id: 10,
        accountId: 10,
        first_name: 'Chris',
        last_name: 'Taylor',
        age: 24,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Brooklyn',
        green_flag: " I love to laugh and bring joy to our relationship, knowing that humor can be a great way to navigate life's challenges.",
        yellow_flag: "I think puppet humor is underrated.",
        red_flag: "Jeff Foxworthy is the greatest comedian of all time.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456152/Portraits/Male/darshan-patel-QJEVpydulGs-unsplash_vxkual.jpg',
    },
    {
        id: 11,
        accountId: 11,
        first_name: 'Nathan',
        last_name: 'Anderson',
        age: 20,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Long Island',
        green_flag: "I take care of my responsibilities and strive to create a stable and secure environment for our relationship.",
        yellow_flag: "There's a right way and a wrong way. Luckily, there's nothing a good Power Point can't explain",
        red_flag: "I consider myself something of an alpha.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456152/Portraits/Male/joseph-gonzalez-iFgRcqHznqg-unsplash_mlk1ao.jpg',
    },
    {
        id: 12,
        accountId: 12,
        first_name: 'Owen',
        last_name: 'Thomas  ',
        age: 30,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Bronx',
        green_flag: "I have interests and hobbies that make me excited about life, and I'm eager to share these passions with you.",
        yellow_flag: "I consider LARPing a way of life, not a hobby.",
        red_flag: "I am in the midst of an ongoing feud with Carol Baskin.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456150/Portraits/Male/julian-myles-I2g6Oe9ElbE-unsplash_h0r3zg.jpg',
    },
    {
        id: 13,
        accountId: 13,
        first_name: 'Henry',
        last_name: 'Jackson',
        age: 28,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Manhattan',
        green_flag: "I'm attuned to my own emotions and yours, allowing us to navigate the ups and downs of life with empathy and understanding.",
        yellow_flag: "The Muppets movie is peak cinema in my opinion.",
        red_flag: "There's like an 80 percent chance Charles Manson is my dad.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456150/Portraits/Male/prince-akachi-4Yv84VgQkRM-unsplash_gwecva.jpg',
    },
    {
        id: 14,
        accountId: 14,
        first_name: 'Caleb',
        last_name: 'Harris',
        age: 38,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Bronx',
        green_flag: "I approach challenges with a positive mindset and am committed to finding solutions that benefit both of us.",
        yellow_flag: "When I don't have problems to solve, I'm pretty good at manufacturing new ones!",
        red_flag: "If you can't handle me at my worst, you don't deserve me at my best.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456149/Portraits/Male/nonsap-visuals-kMJp7620W6U-unsplash_klm74m.jpg',
    },
    {
        id: 15,
        accountId: 15,
        first_name: 'Sebastian',
        last_name: 'Martin',
        age: 28,
        gender: 'male',
        pronouns: 'he/him',
        location: 'Bronx',
        green_flag: "Staying active is a big part of my life, whether it's going for a morning run, hitting the gym, or participating in sports. I believe in the importance of a healthy lifestyle and would love to share my passion for fitness with you.",
        yellow_flag: "Pigeons aren't real and I can prove it.",
        red_flag: "The only book I've ever read is The Four Agreements.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456147/Portraits/Male/piotr-wilk-LcCvM4vZEyg-unsplash_zvmzqs.jpg',
    },
    {
        id: 16,
        accountId: 16,
        first_name: 'Emma',
        last_name: 'Thomas',
        age: 38,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Manhattan',
        green_flag: "I believe in open and honest communication, and I'm always willing to listen and express my thoughts and feelings.",
        yellow_flag: "I also believe honest communication needs to be expressed in iambic pentameter.",
        red_flag: "My dream man is Hugh Hefner (dead or alive)",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456166/Portraits/Female/stefan-stefancik-QXevDflbl8A-unsplash_hxjfss.jpg',
    },
    {
        id: 17,
        accountId: 17,
        first_name: 'Olivia',
        last_name: 'Garcia',
        age: 35,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Bronx',
        green_flag: "I love exploring new destinations and cultures, making each trip an opportunity for us to bond and create shared memories.",
        yellow_flag: "What even is stealing anyway?",
        red_flag: "I'm a card carrying membber of the Flat Earth Society of America",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456164/Portraits/Female/hiki-app-A9rQeI2AdR4-unsplash_iqz8iv.jpg',
    },
    {
        id: 18,
        accountId: 18,
        first_name: 'Sophia',
        last_name: 'Martinez',
        age: 23,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Queens',
        green_flag: "I treat you and others with kindness, respect, and consideration, valuing our differences and boundaries.",
        yellow_flag: "My favorite shirt says Rosé All Day",
        red_flag: "I was a three-time contestant on Fear Factor",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456158/Portraits/Female/christina-wocintechchat-com-0Zx1bDv5BNY-unsplash_y6f7wt.jpg',
    },
    {
        id: 19,
        accountId: 19,
        first_name: 'Ava',
        last_name: 'Robinson',
        age: 36,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Queens',
        green_flag: "I genuinely care about what you have to say, and I enjoy having meaningful conversations with you.",
        yellow_flag: "I am the CEO and founder of a home surveillance equipment company",
        red_flag: "I'm going to need a couple of data points for a quick background check ahead of our first date",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456155/Portraits/Female/hiki-app-YA84k2xRz7c-unsplash_qoatwz.jpg',
    },
    {
        id: 20,
        accountId: 20,
        first_name: 'Mia',
        last_name: 'Clark',
        age: 26,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Queens',
        green_flag: "You can count on me to keep my promises and maintain your trust in our relationship.",
        yellow_flag: "I'm the CEO of a Multi-Level Marketing",
        red_flag: "Can I interest you in a sure-thing business opportunity?",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456154/Portraits/Female/prince-akachi-J1OScm_uHUQ-unsplash_qtf6wp.jpg',
    },
    {
        id: 21,
        accountId: 21,
        first_name: 'Charlotte',
        last_name: 'Lewis',
        age: 35,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Queens',
        green_flag: "My taste in music is eclectic, and I enjoy everything from classical to rock to hip-hop. Whether it's attending concerts, jamming with friends, or simply appreciating the beauty of a well-composed melody, music plays a significant role in my life, and I'd love to explore this world with you.",
        yellow_flag: "Freebird!!!",
        red_flag: "Kid Rock has a restraining order on me",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456153/Portraits/Female/filipp-romanovski-CGKYNN3uuVo-unsplash_bariom.jpg',
    },
    {
        id: 22,
        accountId: 22,
        first_name: 'Amelia',
        last_name: 'Walker',
        age: 25,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Brooklyn',
        green_flag: "While I value our relationship, I also respect the importance of individuality and personal space, allowing us both to grow independently.",
        yellow_flag: "Birds aren't real",
        red_flag: "I was Joan of Arc in my previous incarnation ",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456148/Portraits/Female/good-faces-xmSWVeGEnJw-unsplash_lnb8mr.jpg',
    },
    {
        id: 23,
        accountId: 23,
        first_name: 'Harper',
        last_name: 'Hall',
        age: 35,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Long Island',
        green_flag: "Exploring the beauty of nature through hiking, camping, and outdoor activities is a passion of mine. I believe in the restorative power of the great outdoors and would love to embark on nature-filled adventures with you.",
        yellow_flag: "If you aren't free soloing, it ain't rock climbing",
        red_flag: "Timothy Treadwell is my ex.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456148/Portraits/Female/hiki-app-lh9_ATRPKJQ-unsplash_e2ke7p.jpg',
    },
    {
        id: 24,
        accountId: 24,
        first_name: 'Evelyn',
        last_name: 'Young',
        age: 24,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Long Island',
        green_flag: "I appreciate the world of literature and enjoy discussing books and ideas, fostering intellectual conversations and connection.",
        yellow_flag: "My favorite book is the Necronomicon.",
        red_flag: "This dating app experience reminds me of a poem I once wrote. Can I recite it to you?",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456148/Portraits/Female/christopher-campbell-rDEOVtE7vOs-unsplash_cufzxw.jpg',
    },
    {
        id: 25,
        accountId: 25,
        first_name: 'Abigail',
        last_name: 'Turner',
        age: 33,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Manhattan',
        green_flag: "Trying new restaurants, experimenting with recipes at home, and savoring delicious dishes from around the world are some of my favorite pastimes. ",
        yellow_flag: "I think pizza is gross.",
        red_flag: "The poison pen of my Yelp account is feared by dining establishment throughout the tri-state area.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456148/Portraits/Female/jake-nackos-IF9TK5Uy-KI-unsplash_wjd3tt.jpg',
    },
    {
        id: 26,
        accountId: 26,
        first_name: 'Lily',
        last_name: 'Wright',
        age: 23,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Manhattan',
        green_flag: "I thrive on new experiences and love to plan exciting dates and adventures that keep our relationship fresh and exciting.",
        yellow_flag: "I run a fight club from the basement of my pet grooming business.",
        red_flag: "I'm a sovereign citizen.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456147/Portraits/Female/aiony-haust-3TLl_97HNJo-unsplash_hw2smx.jpg',
    },
    {
        id: 27,
        accountId: 27,
        first_name: 'Zoe',
        last_name: 'White',
        age: 32,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Manhattan',
        green_flag: "I approach challenges with a level head and a willingness to collaborate, ensuring that we can overcome obstacles together.",
        yellow_flag: "Vince McMann is my god father.",
        red_flag: "I need to get out of the country fast, and I don't have time to answer a lot of questions.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456147/Portraits/Female/hiki-app-oz9fHNCUhZc-unsplash_imamae.jpg',
    },
    {
        id: 28,
        accountId: 28,
        first_name: 'Emily',
        last_name: 'Adams',
        age: 32,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Manhattan',
        green_flag: "There's nothing I love more than a morning run.",
        yellow_flag: "Don't ask me about my relationship with Gary Busey.",
        red_flag: "The devil put the dinosaur bones in the ground.",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456147/Portraits/Female/hiki-app-oz9fHNCUhZc-unsplash_imamae.jpg',
    },
    {
        id: 29,
        accountId: 29,
        first_name: 'Grace',
        last_name: 'Bake',
        age: 25,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Brooklyn',
        green_flag: "Visiting art galleries, discussing different art movements, and even creating my own artwork are integral to my life. Art has a way of enriching our perspectives, and I'd be thrilled to share this world of creativity with you.",
        yellow_flag: "I am also an expert gymnast, trapeez artist, and glass cutter.",
        red_flag: "I own an original copy of Edvard Munch's The Scream",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456148/Portraits/Female/hiki-app-7kQ3cdG2rJI-unsplash_ll5fgq.jpg',
    },
    {
        id: 30,
        accountId: 30,
        first_name: 'Sofia',
        last_name: 'Nelson  ',
        age: 22,
        gender: 'female',
        pronouns: 'she/her',
        location: 'Manhattan',
        green_flag: "I cherish close relationships with my family.",
        yellow_flag: "Apparently unicorns aren't a real animal.",
        red_flag: "I'm looking forward to becoming a part of your family!",
        image: 'https://res.cloudinary.com/dxwgp0b41/image/upload/v1694456146/Portraits/Female/rachel-mcdermott-0fN7Fxv1eWA-unsplash_uqu5ov.jpg',
    },
]

//🔥🔥🔥Seed Function🔥🔥🔥
const seedprofiles = async () => {
    try {
      // Use bulkCreate to insert the profile data into the 'profile' table
      const createdprofiles = await profile.bulkCreate(profileData);
      console.log('profiles seeded successfully:', createdprofiles);
    } catch (error) {
      console.error('Error seeding profiles:', error);
    }
  };
  
  // Call the seedprofiles function to seed the data

seedprofiles();

// 🔥🔥🔥Export🔥🔥🔥
module.exports = seedprofiles;